version: "3.6"

services:
  larapi:
    build: .
    container_name: "larapi"
    hostname: "larapi"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/data/doc_root/service/larapi"
    privileged: true
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: "larapi_mysql"
    hostname: "larapi_mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=larapi

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "larapi_phpmyadmin"
    hostname: "larapi_phpmyadmin"
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PORT: 3306
      PMA_PASSWORD: admin
    links:
      - mysql
